#!/usr/bin/env bash

LATEST_VERSION="13"

if [ "$DOCKER_TAG" = "latest" ]; then
	VERSION=$LATEST_VERSION
else
	VERSION=$DOCKER_TAG
fi

BASE_IMAGE=stretch

docker build -t ${IMAGE_NAME} \
	--build-arg=VERSION=$VERSION \
	--build-arg=DOCKER_TAG=$DOCKER_TAG \
	.
